version: '3.9'

services:
  youtubebot:
    container_name: youtubebot
    depends_on:
     - youtubellm
    build:
      context: src
      dockerfile: Dockerfile
    volumes:
      - ./src:/app

  youtubellm:
    container_name: youtubellm
    image: ghcr.io/abetlen/llama-cpp-python:latest
    ports:
      - "7700:8000"
    environment:
      - MODEL=/models/orca-mini-3b.ggufv3.q4_0.bin
    volumes:
      - ./models:/models


